### ISSUE TITLE
legendTitle not working

### ISSUE THREAD

**Issue by hueyrb** [MazamaScience/MazamaSpatialPlots#20]
Maps are great but get this error if I add legendTitle, and doesn't change legendTitle

Error in stateMap(data = example_US_stateObesity, parameter = "obesityRate",  : 
  unused argument (legendTitle = "Uninsured (%)")

stateMap(
	data = example_US_stateObesity,
	parameter = 'obesityRate',
	palette = 'YlOrRd',
	breaks = seq(20, 38, 3),
	conusOnly = TRUE,
	legendTitle = 'Uninsured (%)',
	stateBorderColor = 'black',
	title = "Obesity Rate in U.S."
)

**Comment by jonathancallahan** [comment]
In our rush to get this package out for people to use, we neglected to upgrade the `stateMap()` function with all of the arguments supported by the `countyMap()` function. Just `?stateMap` to see which arguments are supported. I'm adding this to the list of issues we're building up for a 0.2 release.

In the mean time, you can always use functionality from the **tmap** package in this manner:

```
# Create a tmap/ggplot2 object
gg <- 
  stateMap(
    data = example_US_stateObesity,
    parameter = 'obesityRate',
    palette = 'YlOrRd',
    breaks = seq(20, 38, 3),
    conusOnly = TRUE,
    legendTitle = 'Uninsured (%)',
    stateBorderColor = 'black',
    title = "Obesity Rate in U.S."
  ) +
    tmap::tm_layout(
      main.title.size = .9,
      legend.is.portrait = legendIsPortrait,
      legend.show = showLegend,
    )
```

See `?tmap::tm_layout` for the full suite of plot options.

**Comment by hueyrb** [comment]
Hi Jonathan

doesn’t work unless I hashtag out, as shown below

stateMap(
		data = example_US_stateObesity,
		parameter = 'obesityRate',
		palette = 'YlOrRd',
		breaks = seq(20, 38, 3),
		conusOnly = TRUE,
	# 	legendTitle = 'Uninsured (%)',
		stateBorderColor = 'black',
		title = "Obesity Rate in U.S."
	) +
	tmap::tm_layout(
		main.title.size = .9,
		# legend.is.portrait = legendIsPortrait,
		# legend.show = showLegend,
	)

Also, having trouble saving the file with ggsave.  
In RStudio, I just use the export to pdf approach, which works.

Ray

**Comment by jonathancallahan** [comment]
I had corrected my original response. You may have gotten an email with my first edit which has the code you see above.

To save just

1. open the appropriate graphical device with `png()` or `pdf()` or whatever
2. create the ggplot object and `print(gg)`
3. `dev.off()
